TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#==================================================
# build a support library

LIBRARY_IOC += ooEpics

# xxxRecord.h will be created from xxxRecord.dbd
#DBDINC += xxxRecord
# install ooEpics.dbd into <top>/dbd
DBD += ooEpics.dbd

# specify all source files to be compiled and added to the library
#ooEpics_SRCS += xxx

ooEpics_LIBS += $(EPICS_BASE_IOC_LIBS)

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

